//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaoTwo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Function
    {
        public System.Guid FunctionGuid { get; set; }
        public System.Guid ParentGuid { get; set; }
        public string FunctionName { get; set; }
        public string DisplayName { get; set; }
        public int DisplayOrder { get; set; }
        public string ActionUrl { get; set; }
        public string FunctionType { get; set; }
        public bool Enable { get; set; }
        public System.DateTime TimeCreated { get; set; }
    }
}
