//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dao.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccount
    {
        public int ID { get; set; }
        public System.Guid Guid { get; set; }
        public string UserName { get; set; }
        public string PasswordHash { get; set; }
        public string Email { get; set; }
        public bool IsEmailValidated { get; set; }
        public string MobilePhone { get; set; }
        public bool IsMobilePhoneValidated { get; set; }
        public string Status { get; set; }
        public int CountVisited { get; set; }
        public string IPv4LastVisited { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime TimeCreated { get; set; }
        public System.DateTime TimeLastVisited { get; set; }
        public string BindingCode { get; set; }
        public string OwnerId { get; set; }
        public string OwnerType { get; set; }
    }
}
